when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
test_route:
    path: /test
    controller: App\Controller\SecurityController::test
